import numpy as np
import hashlib


def bytes_to_bits(byte_data):
    """
    Convert bytes or bytearray into a list of 0/1 bits (MSB first).
    """
    bits = []
    for byte in byte_data:
        for i in range(7, -1, -1):
            bits.append((int(byte) >> i) & 1)
    return bits


def bits_to_bytes(bits):
    """
    Convert a list of 0/1 bits back into bytes (MSB first).
    Pads with 0 bits if the length is not a multiple of 8.
    """
    byte_array = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bits):
                byte = (byte << 1) | int(bits[i + j])
            else:
                byte = (byte << 1)
        byte_array.append(byte)
    return bytes(byte_array)


def set_lsb(value, bit):
    """
    Set the least significant bit (LSB) of an integer/uint8.
    """
    return (int(value) & 0xFE) | (int(bit) & 1)


def get_lsb(value):
    """
    Get the least significant bit (LSB) of an integer/uint8.
    """
    return int(value) & 1


def set_msb(value, bit):
    """
    Set the most significant bit (MSB) of an integer/uint8.
    """
    return (int(value) & 0x7F) | ((int(bit) & 1) << 7)


def get_msb(value):
    """
    Get the most significant bit (MSB) of an integer/uint8.
    """
    return (int(value) >> 7) & 1


def get_new_pixel_positions(orig_shape, scale):
    """
    Get all new pixel positions generated by upscaling that are not
    on the original coordinate grid (row % scale != 0 or col % scale != 0).
    orig_shape: (H, W) of the original image before scaling.
    scale: integer scaling factor (e.g. 4).
    """
    H, W = orig_shape[:2]
    new_positions = []
    for row in range(H * scale):
        for col in range(W * scale):
            if row % scale != 0 or col % scale != 0:
                new_positions.append((row, col))
    return new_positions


def generate_xor_key(new_positions, message_length):
    """
    Generate a deterministic dynamic XOR keystream from the new pixel positions
    using SHA-256 hashing.
    """
    if message_length <= 0:
        return []
    
    pos_bytes = bytearray()
    for row, col in new_positions:
        pos_bytes += row.to_bytes(2, 'big') + col.to_bytes(2, 'big')

    # Hash positions with SHA-256 (32 bytes = 256 bits)
    hash_bytes = hashlib.sha256(pos_bytes).digest()

    # Repeat bitstream to match required message length
    key_bits = bytes_to_bits(hash_bytes)
    repeats = (message_length // len(key_bits)) + 1
    return (key_bits * repeats)[:message_length]
